### ISSUE TITLE
Define skills of Okon for BT

### ISSUE THREAD

**Issue by VECTR0** [knr-auv/autonomy#1]
define what Okon can do
- physical activities
- sensor readings

**Comment by VECTR0** [comment]
Physical changes:
- set rotation yaw
- set linear velocity
- set depth
- release grip (griping by moving the whole robot down)

Virtual changes:
- get detection (class, bbox, distance)
- wait
- get color blob under (check for specified colored blob using down camera)

**Comment by mpfmorawski** [comment]
I think that we can close this issue because the general actions have already been defined. And we can discuss further actions (for example, to the next tasks) in the next designated Issues.

What do you think about it, @miki87278?

**Comment by VECTR0** [comment]
I agree. Defined actions are good for now and that's a good idea to add actions in separate issues
